### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by shurijoc** [ym0628/arisou#59]
こちらにレビュー内容書かせていただきます！

就活を踏まえて、以下の観点からサービスとリポジトリを元にレビューさせていただきますね。

```markdown
💡 就活レビュー観点

1. 課題に対してサービス内で適切な解決策となる機能を提供できているか・READMEに書いているか
2. 就活において十分な技術力を示せる機能を実装しているか
3. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
```

### 1,3について

パチスロやったことがないですが、前提知識から課題感、解決策までとてもわかりやすくてとても良いと思います。
見た目もシンプルでやるべきことが明確なのでとても良いと思います！

### 2について

こちらもtools_controllerでビジネスロジックの実装をしているのが良いですね。

1点、ファットコントローラーと言う、コントローラーにビジネスロジックを書いてしまっている状態になっているのでリファクタリングしてコントローラーの記述は極力減らしましょう。
コツとしては以下の2点意識してください！

1. モデルのメソッドに寄せる

コントローラーの記述をモデルに書くイメージはこのような想定です。
https://qiita.com/konchan_exbaka/items/6a7a1bfdc1217135ab66

2. ほとんど同じ事を書いている場合は1つにまとめてloop処理をする

例えば以下のような記述の場合このように書けるかと！

before
```rb
    if @ones_place_group[0].present?
      @sum0 = 0
      @ones_place_group[0].each do |_number, medal|
        @sum0 += medal
      end
      @average0 = (@sum0 / @each_denominator).round(1)
    end

    if @ones_place_group[1].present?
      @sum1 = 0
      @ones_place_group[1].each do |_number, medal|
        @sum1 += medal
      end
      @average1 = (@sum1 / @each_denominator).round(1)
    end
```

after
```
def calculate_average(medals)
  return nil if medals.empty?

  sum = medals.values.sum
  (sum / medals.size.to_f).round(1)
end

@average0 = calculate_average(@ones_place_group[0]) if @ones_place_group[0].present?
@average1 = calculate_average(@ones_place_group[1]) if @ones_place_group[1].present?
```

少し長くなってしまいましたがMVPとしてLGTMです！
本リリース（就活で先方に提出する）前にtools_controllerのリファクタリングは完了しておくようにお願いします！

![nise_rantekun](https://github.com/ym0628/arisou/assets/6407534/835f2e6c-e02c-42d9-b1e5-24be77bdf1ac)

**Comment by shurijoc** [comment]
このIssueも確認しましたらcloseで大丈夫ですので 🙏

**Comment by ym0628** [comment]
ご確認いただきありがとうございました。
コントローラーのロジックについて、アドバイス頂きありがとうございます。
この後、対応してまいります。
